#!/bin/fish
# base installation for my awesome config
# surely there being package that installed before
# like: git vim yadm

sudo pacman -Syy --needed git yadm which base-devel python
set PARU_PATH "$HOME/.local/lib/paru"
which paru &>/dev/null || begin
    git clone https://aur.archlinux.org/paru.git "$PARU_PATH"
    cd "$PARU_PATH" || exit 1
    makepkg -si
end

which powershell.exe &>/dev/null && set is_wsl true || set is_wsl false
echo "is wsl: " $is_wsl

set 2install

# gtk theme and icon
set -a 2install whitesur-gtk-theme orchis-theme-git orchis-kde-theme-git papirus-icon-theme-git bibata-cursor-theme-bin
# English serif and sans-serif fonts
set -a 2install ttf-sarasa-gothic adobe-source-serif-fonts ttf-dejavu
# coding fonts
set -a 2install nerd-fonts-{mononoki, ubuntu-mono,fira-code} ttf-recursive
# symbol and unicode fonts
set -a 2install ttf-twemoji
# utilities
set -a 2install xclip

# wsl have built in x server so display and windows manager are not needed
if not $is_wsl
    # X and windows manager
    set -a 2install linux-headers nvidia-dkms nvidia-settings xorg-server awesome-git lain-git picom-ibhagwan-git
    # display manager and screen locker
    set -a 2install lightdm lightdm-webkit-theme-aether betterlockscreen xidlehook
    # gui system tools
    set -a 2install rofi feh xcape
    set -a 2install lxqt-policykit gnome-keyring
    set -a 2install redshift gparted xcolor pamac-aur
    # symbol and unicode fonts for desktop environment
    set -a 2install ttf-material-design-icons-git
else
    # subsystemctl, for ssh into wsl
    set subspath "~/.local/lib/subsystemctl"
    ls "$subspath" &>/dev/null || begin
        curl -Lo "$subspath"/PKGBUILD --create-dirs https://github.com/sorah/arch.sorah.jp/blob/master/aur-sorah/PKGBUILDs/subsystemctl/PKGBUILD && cd "$subspath" && makepkg -si
    end
end

paru -S --needed $2install

# rofi font
set AGAVE_PATH "$HOME/.local/lib/agave"
fc-list | grep agave &>/dev/null || begin
    curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Agave.zip
    7z x Agave.zip -o"$AGAVE_PATH" && rm Agave.zip
    cd "$AGAVE_PATH" && fd Windows -x rm && cp (ls | grep -v Windows) ~/.local/share/fonts
end
