#!/bin/bash

paru -S --needed exa fd ripgrep\
	cmake python3 python-pip\
	xclip maim\
	gnuplot\
	neofetch\
	nerd-fonts-mononoki\
	whitesur-gtk-theme-git\
	tela-icon-theme-git\
	bibata-cursor-theme-bin\
	noto-fonts noto-fonts-emoji
	# awesome-git\
	# picom-ibhagwan-git\
	# rofi\
	# ttf-material-icons-git\
	# ttf-sarasa-gothic

pip install isort\
	pipenv\
	nose\
	pytest
	
TPM_PATH="$HOME/.tmux/plugins/tpm"
[ -d "$TPM_PATH" ] || {
  git clone https://github.com/tmux-plugins/tpm "$TPM_PATH"
}

LAIN_PATH="$HOME/softwares/lain"
[ -d "$LAIN_PATH" ] || {
  git clone https://github.com/lcpz/lain.git "$LAIN_PATH"
  ln -s "$LAIN_PATH" "$HOME/.config/awesome/lain"
}
