#!/bin/bash

paru -S --needed cmake python3 python-pip base-devel man\
    neovim emacs\
    polkit-kde-agent\
    ttf-linux-libertine gentium-plus-font adobe-source-serif-fonts\
    nerd-fonts-{mononoki,fira-code}\
    wqy-microhei ttf-{arphic-ukai,sarasa-gothic}\
    ttf-twemoji ttf-material-design-icons-git ttf-symbola\
    whitesur-gtk-theme-git papirus-icon-theme-git bibata-cursor-theme-bin\
    fcitx5-im fcitx5-rime rime-cloverpinyin fcitx5-nord\
    fd ripgrep\
    clang glslang\
    gnuplot direnv-bin shellcheck-bin prettier clang-format-static-bin\
    mu isync\
    p7zip xclip maim\
    inetutils\
    exa tmux ranger neofetch
# awesome-git picom-ibhagwan-git rofi\

# required by doom emacs
pip install\
    black python-lsp-server\
    isort pipenv nose pytest pyflakes

TPM_PATH="$HOME/.tmux/plugins/tpm"
[ -d "$TPM_PATH" ] || {
    git clone https://github.com/tmux-plugins/tpm "$TPM_PATH"
}

LAIN_PATH="$HOME/softwares/lain"
[ -d "$LAIN_PATH" ] || {
    git clone https://github.com/lcpz/lain.git "$LAIN_PATH"
    ln -s "$LAIN_PATH" "$HOME/.config/awesome/lain"
}

PARU_PATH="$HOME/softwares/paru"
[ -d "$PARU_PATH" ] || {
    git clone https://aur.archlinux.org/paru.git "$PARU_PATH"
    cd "$PARU_PATH" || return 1
    makepkg -si
}

COMICSHANNS_PATH="$HOME/softwares/comic-shanns"
[ -d "$COMICSHANNS_PATH" ] || {
    git clone https://github.com/shannpersand/comic-shanns.git "$COMICSHANNS_PATH"
    cd "$COMICSHANNS_PATH" || return 1
    cp v2/* ~/.local/share/fonts
}

AGAVE_PATH="$HOME/softwares/agave"
[ -d "$AGAVE_PATH" ] || {
    cd ~/softwares && curl -LO https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Agave.zip
    7z x Agave.zip -o"$AGAVE_PATH"
    cd "$AGAVE_PATH" && fd Windows -x rm && cp $(ls | grep -v Windows) ~/.local/share/fonts
}


#generate all system wide authorized keys, needed for sshd to run
#ssh-keygen -A
#generate a ssh key if not exist (add public key to github).
#ssh-keygen
