title="packages for a fresh system"
# use =yadm list | grep "\.config" | cut -d '/' -f 2 | uniq -c | sort -n=
# to see all your config directory in ".config"

# default select for module/directory
enable_default=false

[system]
packages=[
    "gnome-keyring",
    "grub",
    "lxqt-policykit",
    "ntfs-3g",
    "os-prober",
    "usbutils"
]

[network]
packages=[
    "iptables-nft",
    # "iw",
    # "mtr",
    "network-manager-applet",
    "networkmanager",
    "sshguard"
]

[nvidia]
packages=["nvidia", "nvidia-utils", "nvidia-settings", "nvidia-prime"]

[amd]
# for cpu with integrated graphics
packages=[
    "amd-ucode",
    "amdgpu_top-bin",
    "libva-mesa-driver",
    "libva-utils",
    "mesa-utils",
    "xf86-video-amdgpu"
]

[sound]
packages=[
    "pipewire",
    "pipewire-alsa",
    "pipewire-jack",
    "pipewire-pulse",
    "playerctl",
    "wireplumber"
]

[sddm]
packages=[
    "mons",
    "sddm",
    "sddm-sugar-light",
    "xorg-server"
]

[awesome]
directory="~/.config/awesome/"
depends_on=["sddm"]
packages=[
    "awesome-git",
    "betterlockscreen",
    "lain-git",
    "lm_sensors",
    "lua-inspect",
    "luarocks",
    "maim",
    "pacman-contrib",
    "picom",
    "python-pywal",
    "redshift",
    "ttf-comic-shanns-v2",
    "ttf-material-design-icons-git",
    "ttf-sarasa-gothic-sc",
    "upower",
    "xcape",
    "xidlehook",
    "xsel",
    "xsettingsd"
]

[doom]
enabled=true
directory="~/.config/doom/"
packages=[
    "emacs-nativecomp",
    "fd",
    "ripgrep"
]

[browser]
packages=["librewolf-bin"]

[terminal]
packages=["alacritty", "dracula-alacritty-git"]

[fish]
enabled=true
packages=["fish", "starship", "xorg-xdpyinfo", "fish-done"]

["shell-utilities"]
enabled=true
packages=[
    "bat",
    # "bc",
    "bpytop",
    # "dragon-drop",
    "exa",
    "gdu-bin",
    # "nvtop",
    "man-db",
    "neofetch",
    "p7zip",
    # "ranger",
    # "tmsu-bin",
    # "tokei",
    "which",
    # "xcolor",
    # "inxi"
]

[gtk]
enabled=true
packages=[
    "bibata-cursor-theme-bin",
    # "gtk-engine-murrine",
    "papirus-icon-theme",
    "ttf-sarasa-gothic-sc"
]

[qt5ct]
enabled=false
# depends on kvantum
packages=[
    "kvantum",
    "kvantum-theme-orchis-git",
    "papirus-icon-theme",
    "qt5-styleplugins",
    "qt5ct"
]

[fontconfig]
# minimized
enabled=false
packages=[
    "ttf-opensans",
    "adobe-source-serif-fonts",
    "ttf-lxgw-wenkai",
    "ttf-sarasa-gothic-sc",
    "noto-fonts-emoji",
    "ttf-firacode-nerd"
]

[input_method]
packages=[
    "fcitx5-im",
    "fcitx5-nord",
    "fcitx5-rime",
    "rime-cloverpinyin"
]

[rofi]
packages=["rofi", "rofimoji"]

[editor]
packages=["vscodium-bin-marketplace", "neovim"]

[proxy]
packages=["xray-bin", "qv2ray"]

[paper]
packages=["miktex-git", "zotero-bin"]

[remote]
packages=[
    "barrier",
    "openssh",
    "realvnc-vnc-viewer",
    "scrcpy",
    "tigervnc-server"
]

[bluetooth]
packages=["blueman", "bluez", "bluez-utils"]

[virtual]
packages=[
    "dnsmasq",
    "edk2-ovmf",
    "libvirt",
    "qemu-desktop",
    "swtpm",
    "virt-manager"
]

[amuse]
packages=[
    "mpv",
    "nomacs",
    "picacg-qt-appimage",
    "r3play-appimage",
    "spotify",
    "steam",
    "telegram-desktop"
]

[benchmark]
packages=["s-tui", "kdiskmark", "blender-benchmark", "crazydiskinfo"]

[files]
packages=["baidunetdisk-bin", "nextcloud-client", "xunlei-bin"]

[dev]
packages=[
    "blender",
    "docker",
    "docker-compose",
    "ffmpegthumbnailer",
    "gcc",
    "gimp",
    "jdk-openjdk"
]

[devices]
packages=[
    "galaxybudsclient-bin",
    "i2c-tools",
    "obinskit",
    "openrgb-bin",
    "via-bin"
]

["font-manager"]
# those are all my favorite fonts
packages=[
    "font-manager",
    # sans
    "ttc-iosevka-aile",
    "ttf-fira-sans",
    "ttf-opensans",
    "ttf-sarasa-gothic-sc",
    # serif
    "adobe-source-serif-fonts",
    "gentium-plus-font",
    # code
    "ttf-agave-nerd",
    "ttf-bqn386-git",
    "ttf-firacode-nerd",        # ligature
    "ttf-recursive",
    # ui
    "ttf-comic-shanns-v2",
    # emoji
    "ttf-material-design-icons-git",
    "noto-fonts-emoji",
    "quirvira",
    # chinese
    "ttf-arphic-ukai",
    "ttf-kose-git",
    "ttf-lxgw-wenkai",
    "ttf-yozai-font",
    "ttf-lxgw-neo-xihei",
    "wqy-microhei"
]
