#! /bin/sh
# https://superuser.com/a/1128905/636739
# The default path of this script should be ~/.xsession,
# move it to here with a customized /etc/sddm.conf.d/Xsession

# systemctl --user import-environment PATH DBUS_SESSION_BUS_ADDRESS
systemctl --no-block --user start xsession.target
