#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "material"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_shell = 'terminal'
default_height = 30

# -- user settings --
[[layers]]
name = "sudo"

[[layers]]
name = "tmux"

[[layers]]
name = "lang#python"

[[layers]]
  name = "lang#c"
  enable_clang_syntax_highlight = true

[[layers]]
  name = "format"

[[custom_plugin]]
repo = "godlygeek/tabular"
merged = false

[[custom_plugin]]
repo = "scrooloose/nerdcommenter"

[[layers]]
  name = "colorscheme"
  # random_theme = true
  frequency = "15m"

[options]
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    default_incident = 4
    expand_tab = true
