# https://github.com/alacritty/alacritty/issues/7473
import = ["/usr/share/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 13.5

[font.bold]
family = "mononokiLiga Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "mononokiLiga Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "mononokiLiga Nerd Font Mono"

[font.normal]
family = "mononokiLiga Nerd Font Mono"
style = "Regular"

[window]
decorations = "none"
dynamic_title = true
dynamic_padding = true
opacity = 0.75
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 7
y = 7
